### ISSUE TITLE
when I convert with Caffe to TensorFlow method， I got wrong score 0.95353949

### ISSUE THREAD

**Issue by hdmjdp** [mdietrichstein/tensorflow-open_nsfw#7]
And I have found the difference is between model.py. Can you show me your convert methods in detail?
thanks

**Comment by mdietrichstein** [comment]
I have used [caffe-tensorflow](https://github.com/ethereon/caffe-tensorflow/) to extract the model weights. The model (`model.py`) was created by looking at the original implementation and manually porting it over to tensorflow.

There were some adaptions necessary regarding the padding layers since caffe and tensorflow have [different approaches](https://stackoverflow.com/questions/42924324/tensorflows-asymmetric-padding-assumptions) there.
